### ISSUE TITLE
Issue with running get_sequence_type

### ISSUE THREAD

**Issue by BioMEC** [sanger-pathogens/mlst_check#65]
I get this error when running get_sequence type after installing mlst_check using 'cpan Bio::MLST::Check' on two different Linux machines. Is this a fixable error or something of my wrongdoing?

Thank you in advance,
Matt

get_sequence_type -s "Clostridium difficile" -d 8 *.fa
Smartmatch is experimental at /home/matthew/perl5/lib/perl5/Bio/MLST/FilterAlleles.pm line 28.
readdir() attempted on invalid dirhandle $dh at /home/matthew/perl5/lib/perl5/Bio/MLST/SearchForFiles.pm line 26.
rewinddir() attempted on invalid dirhandle $dh at /home/matthew/perl5/lib/perl5/Bio/MLST/SearchForFiles.pm line 31.
readdir() attempted on invalid dirhandle $dh at /home/matthew/perl5/lib/perl5/Bio/MLST/SearchForFiles.pm line 32.
Nothing found for species: Clostridium difficile

**Comment by andrewjpage** [comment]
Hi,
Please install the latest version which should fix these issues. Please also take care to read the installation instructions as there are dependancies not installed by CPAN
Andrew
