### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by happykhan** [sanger-pathogens/mlst_check#68]
There is a stub at the end of the GPL licence that you probably want to delete or modify 

See: https://github.com/sanger-pathogens/mlst_check/blob/master/GPL-LICENSE#L627

>                      END OF TERMS AND CONDITIONS
> 
>             How to Apply These Terms to Your New Programs
> 
etc..

**Comment by andrewjpage** [comment]
Thanks, I've made the change.
