### ISSUE TITLE
download_mlst_databases Could not connect to https://pubmlst.org/data/dbases.xml

### ISSUE THREAD

**Issue by novitch** [sanger-pathogens/mlst_check#77]
Hi,
I run into an issue when trying to use download_mlst_databases : here is the errstd:
Could not connect to https://pubmlst.org/data/dbases.xml

What should I do ?

Thanks

Novitch

**Comment by andrewjpage** [comment]
Are you behind a proxy? For connection issues I would recommend talking to your IT support.
